name: simplistic_calculator
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  fluent_ui: ^4.0.0
  fluentui_system_icons: ^1.1.168
  flutter:
    sdk: flutter
  flutter_layout_grid: ^2.0.1
  flutter_riverpod: ^2.0.2
  math_expressions: ^2.3.0
  window_size: 
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
