name: simple_shader
description: Using a shader, simply.
publish_to: 'none'
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.9.0-0

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.0

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  shaders:
    - shaders/simple.frag
