name: compass_server
description: A server app using the shelf package and Docker.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  compass_shared:
    path: ../shared

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.24.0
