name: charts_flutter
version: 0.6.0
description: Material Design charting library for flutter.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  # Pointing this to a local path allows for pointing to the latest code
  # in Github for open source development.
  #
  # The pub version of charts_flutter will point to the pub version of charts_common.
  # The latest pub version is commented out and shown below as an example.
  # charts_common: 0.6.0
  charts_common:
    path: ../common/
  collection: ^1.14.5
  flutter_web: any
  intl: ^0.15.2
  logging: any
  meta: ^1.1.1


dev_dependencies:
  mockito:
  flutter_web_test: any
  test: ^1.3.0

# flutter_web packages are not published to pub.dartlang.org
# These overrides tell the package tools to get them from GitHub
dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
