name: federated_plugin_example
description: Demonstrates how to use the federated_plugin plugin.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  federated_plugin:
    path: ../
  cupertino_icons: ^1.0.2

dev_dependencies:
  analysis_defaults:
    path: ../../../../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
