version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "add_to_app/android_view/flutter_module_using_plugin/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "add_to_app/books/flutter_module_books/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "add_to_app/fullscreen/flutter_module/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "add_to_app/multiple_flutters/multiple_flutters_module/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "add_to_app/plugin/flutter_module_using_plugin/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "add_to_app/prebuilt_module/flutter_module/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "android_splash_screen/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "animations/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "desktop_photo_search/fluent_ui/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "desktop_photo_search/material/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/federated_plugin/federated_plugin/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/federated_plugin/federated_plugin/example/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/federated_plugin/federated_plugin_macos/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/federated_plugin/federated_plugin_platform_interface/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/federated_plugin/federated_plugin_web/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/federated_plugin/federated_plugin_windows/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/linting_tool/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "experimental/web_dashboard/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "flutter_maps_firestore/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "form_app/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "infinite_list/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "ios_app_clip/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "isolate_example/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "jsonexample/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "navigation_and_routing/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "null_safety/null_safe_app/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "null_safety/null_unsafe_app/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "place_tracker/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "platform_channels/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "platform_design/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "platform_view_swift/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "provider_counter/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "provider_shopper/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "simplistic_calculator/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "testing_app/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "veggieseasons/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "web/charts/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "web/github_dataviz/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "web/particle_background/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "web/samples_index/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "web/_tool/"
    schedule:
      interval: "daily"
