name: flutter_module_using_plugin
description: An example Flutter module that uses a plugin.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  url_launcher: ^6.0.6
  sensors: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.3

flutter:
  uses-material-design: true

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: dev.flutter.example.flutter_module_using_plugin
    iosBundleIdentifier: dev.flutter.example.flutterModuleUsingPlugin
