name: platform_channels
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  go_router: ">=6.0.0 <8.0.0"

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
