name: jsonexample
description: A demonstration of JSON parsing
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0
  built_collection: ^5.0.0
  built_value: ^8.2.2

  flutter:
    sdk: flutter

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  built_value_generator: ^8.2.2
  json_serializable: ^6.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
