name: isolate_example
description: A Flutter sample to demonstrate isolates
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
