name: place_tracker
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_maps_flutter:
    git:
      url: git@github.com:ditman/plugins.git
      path: packages/google_maps_flutter/google_maps_flutter
      ref: gmaps-web
  google_maps_flutter_web:
    git:
      url: git@github.com:ditman/plugins.git
      path: packages/google_maps_flutter/google_maps_flutter_web
      ref: gmaps-web
  provider: ^4.0.0
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  assets:
    - assets/

  uses-material-design: true
