name: place_tracker
description: A sample place tracking app.
publish_to: 'none'
version: 1.0.1+2
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  provider: ^6.0.0
  go_router: ^12.0.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  uuid: ^4.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
