name: form_app
description: A sample demonstrating different types of forms and best practices
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  intl: any
  http: ^0.12.0
  mockito: 4.1.1
  json_annotation: ^3.0.0
  english_words: ^3.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.0.0
  build_runner: ^1.10.0
flutter:
  uses-material-design: true
