name: gallery
description: A resource to help developers evaluate and use Flutter.

version: 2.2.0+020200

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  flutter_localized_locales:
  cupertino_icons: ^0.1.2
  rally_assets: 1.0.0
  meta:
  scoped_model:
  shrine_images: ^1.1.2
  flare_flutter: ^1.6.5
  url_launcher: ^5.1.6
  shared_preferences: ^0.5.4+8
  collection: ^1.14.0
  flutter_gallery_assets: 0.1.9+2
  package_info: ^0.4.0+13
  google_fonts: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  grinder: ^0.8.0
  string_scanner: 1.0.5

flutter:
  assets:
    - fonts/google_fonts/
    - assets/demos/
    - assets/studies/
    - assets/icons/cupertino/
    - assets/icons/material/
    - assets/icons/reference/
    - assets/icons/settings/
    - assets/logo/
    - assets/splash_effects/
    - packages/rally_assets/logo.png
    - packages/rally_assets/thumb.png
    - assets/crane/logo/
    - assets/crane/destinations/
    - packages/flutter_gallery_assets/places/india_chennai_flower_market.png
    - packages/flutter_gallery_assets/places/india_thanjavur_market.png
    - packages/flutter_gallery_assets/places/india_tanjore_bronze_works.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_merchant.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple.png
    - packages/flutter_gallery_assets/places/india_pondicherry_salt_farm.png
    - packages/flutter_gallery_assets/places/india_chennai_highway.png
    - packages/flutter_gallery_assets/places/india_chettinad_silk_maker.png
    - packages/flutter_gallery_assets/places/india_tanjore_thanjavur_temple_carvings.png
    - packages/flutter_gallery_assets/places/india_chettinad_produce.png
    - packages/flutter_gallery_assets/places/india_tanjore_market_technology.png
    - packages/flutter_gallery_assets/places/india_pondicherry_beach.png
    - packages/flutter_gallery_assets/places/india_pondicherry_fisherman.png
    - packages/shrine_images/diamond.png
    - packages/shrine_images/slanted_menu.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg
    - packages/shrine_images/7-0.jpg
    - packages/shrine_images/8-0.jpg
    - packages/shrine_images/9-0.jpg
    - packages/shrine_images/10-0.jpg
    - packages/shrine_images/11-0.jpg
    - packages/shrine_images/12-0.jpg
    - packages/shrine_images/13-0.jpg
    - packages/shrine_images/14-0.jpg
    - packages/shrine_images/15-0.jpg
    - packages/shrine_images/16-0.jpg
    - packages/shrine_images/17-0.jpg
    - packages/shrine_images/18-0.jpg
    - packages/shrine_images/19-0.jpg
    - packages/shrine_images/20-0.jpg
    - packages/shrine_images/21-0.jpg
    - packages/shrine_images/22-0.jpg
    - packages/shrine_images/23-0.jpg
    - packages/shrine_images/24-0.jpg
    - packages/shrine_images/25-0.jpg
    - packages/shrine_images/26-0.jpg
    - packages/shrine_images/27-0.jpg
    - packages/shrine_images/28-0.jpg
    - packages/shrine_images/29-0.jpg
    - packages/shrine_images/30-0.jpg
    - packages/shrine_images/31-0.jpg
    - packages/shrine_images/32-0.jpg
    - packages/shrine_images/33-0.jpg
    - packages/shrine_images/34-0.jpg
    - packages/shrine_images/35-0.jpg
    - packages/shrine_images/36-0.jpg
    - packages/shrine_images/37-0.jpg

  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: fonts/GalleryIcons.ttf
    # TODO: Remove once google_fonts supports condensed fonts
    - family: Roboto Condensed
      fonts:
        - asset: packages/rally_assets/RobotoCondensed-Light.ttf
          weight: 400
        - asset: packages/rally_assets/RobotoCondensed-Bold.ttf
          weight: 700

