name: gallery
description: A resource to help developers evaluate and use Flutter.

version: 2.0.0+7

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:
  duration:
  cupertino_icons: ^0.1.2
  rally_assets: 1.0.0
  meta:
  scoped_model:
  shrine_images: ^1.1.2
  flare_flutter: ^1.6.5
  url_launcher: ^5.1.6
  url_launcher_web: ^0.1.0
  url_launcher_fde:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      ref: a075c245ffdfc17409a3fff12517cf416aa77c87
      path: plugins/flutter_plugins/url_launcher_fde
  flutter_localized_countries:
    git:
      url: git://github.com/guidezpl/flutter-localized-countries.git
      ref: 76bfbf9654c3842d735181383f7ab86c312a2483
  shared_preferences: ^0.5.4+8
  collection: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  grinder: ^0.8.0

flutter:
  assets:
    - assets/demos/
    - assets/studies/
    - assets/icons/cupertino/
    - assets/icons/material/
    - assets/icons/reference/
    - assets/icons/settings/
    - assets/logo/
    - assets/splash_effects/
    - packages/rally_assets/logo.png
    - packages/rally_assets/thumb.png
    - assets/crane/logo/
    - assets/crane/destinations/
    - packages/shrine_images/diamond.png
    - packages/shrine_images/slanted_menu.png
    - packages/shrine_images/0-0.jpg
    - packages/shrine_images/1-0.jpg
    - packages/shrine_images/2-0.jpg
    - packages/shrine_images/3-0.jpg
    - packages/shrine_images/4-0.jpg
    - packages/shrine_images/5-0.jpg
    - packages/shrine_images/6-0.jpg
    - packages/shrine_images/7-0.jpg
    - packages/shrine_images/8-0.jpg
    - packages/shrine_images/9-0.jpg
    - packages/shrine_images/10-0.jpg
    - packages/shrine_images/11-0.jpg
    - packages/shrine_images/12-0.jpg
    - packages/shrine_images/13-0.jpg
    - packages/shrine_images/14-0.jpg
    - packages/shrine_images/15-0.jpg
    - packages/shrine_images/16-0.jpg
    - packages/shrine_images/17-0.jpg
    - packages/shrine_images/18-0.jpg
    - packages/shrine_images/19-0.jpg
    - packages/shrine_images/20-0.jpg
    - packages/shrine_images/21-0.jpg
    - packages/shrine_images/22-0.jpg
    - packages/shrine_images/23-0.jpg
    - packages/shrine_images/24-0.jpg
    - packages/shrine_images/25-0.jpg
    - packages/shrine_images/26-0.jpg
    - packages/shrine_images/27-0.jpg
    - packages/shrine_images/28-0.jpg
    - packages/shrine_images/29-0.jpg
    - packages/shrine_images/30-0.jpg
    - packages/shrine_images/31-0.jpg
    - packages/shrine_images/32-0.jpg
    - packages/shrine_images/33-0.jpg
    - packages/shrine_images/34-0.jpg
    - packages/shrine_images/35-0.jpg
    - packages/shrine_images/36-0.jpg
    - packages/shrine_images/37-0.jpg

  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: fonts/GalleryIcons.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: fonts/Oswald-Medium.ttf
          weight: 500
    - family: Roboto Condensed
      fonts:
        - asset: packages/rally_assets/RobotoCondensed-Light.ttf
          weight: 400
        - asset: packages/rally_assets/RobotoCondensed-Regular.ttf
          weight: 500
        - asset: packages/rally_assets/RobotoCondensed-Bold.ttf
          weight: 700
    - family: Eczar
      fonts:
        - asset: packages/rally_assets/Eczar-Regular.ttf
          weight: 400
        - asset: packages/rally_assets/Eczar-SemiBold.ttf
          weight: 600
        - asset: packages/rally_assets/Eczar-Bold.ttf
          weight: 700
    # Crane font
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Light.ttf
          weight: 300
        - asset: fonts/Raleway-Regular.ttf
          weight: 400
        - asset: fonts/Raleway-Medium.ttf
          weight: 500
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 600
    # Shrine font
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-Bold.ttf
          weight: 600
    # Code font
    - family: Roboto Mono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 500

