name: analysis_defaults
description: Analysis defaults for flutter/samples
publish_to: none

environment:
  sdk: ^3.1.0

# NOTE: Code is not allowed in this package. Do not add dependencies.
dependencies:
  flutter_lints: ^3.0.0