name: analysis_defaults
description: Analysis defaults for flutter/samples
publish_to: none

environment:
  sdk: ^3.3.1

# NOTE: Code is not allowed in this package. Do not add more dependencies.
# The `flutter_lints` dependency is required for `lib/flutter.yaml`.
dependencies:
  flutter_lints: ^3.0.0
