name: animations
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.0
  go_router: ^14.0.0
  window_size: # plugin is not yet part of the flutter framework
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SpecialElite
      fonts:
        - asset: fonts/SpecialElite-Regular.ttf
