name: samples_index
description: A visual index of Flutter samples
homepage: https://github.com/flutter/samples/tree/main/web/samples_index
version: 0.0.1

environment:
  sdk: ^3.0.0

dependencies:
  json_annotation: ^4.8.1
  path: ^1.8.3
  yaml: ^3.1.2
  mdc_web: ^0.6.0
  sass_builder: ^2.2.1
  checked_yaml: ^2.0.3
  webdriver: ^3.0.2
  html: ^0.15.3

dev_dependencies:
  grinder: ^0.9.4
  flutter_lints: ^2.0.1
  test: ^1.24.2
  json_serializable: ^6.6.2
  build: ^2.4.0
  build_runner: ^2.4.2
  build_web_compilers: ^4.0.3
  image: ">=3.2.0 <5.0.0"

# package:mdc_web needs to upgrade the version of material-components-web 12.0.0
# or above, which includes this fix for the division operator:

# https://github.com/material-components/material-components-web/pull/7158
#
# Until then, dart-sass produces a warning that this operator is being removed
# in favor of calc().
#
# See this issue for details:
# https://github.com/dart-lang/dart-pad/issues/2388
dependency_overrides:
  sass: ^1.62.0