name: samples_index
description: A visual index of Flutter samples
homepage: https://github.com/flutter/samples_index
version: 0.0.1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  json_annotation: ^4.0.1
  path: ^1.6.0
  yaml: ^3.0.0
  mdc_web: ^0.6.0
  sass_builder: ^2.1.0
  checked_yaml: ^2.0.1
  webdriver: ^3.0.0
  html: ^0.15.0
dev_dependencies:
  grinder: ^0.9.0
  flutter_lints: ^1.0.0
  test: ^1.17.10
  json_serializable: ^6.1.5
  build: ^2.0.3
  build_runner: ^2.0.6
  build_web_compilers: ^3.0.0
  tuneup: ^0.3.8
  image: ^3.0.2
# waiting for the next material-components-web release.
# Once released, it will need to be rolled into package:mdc_web.
#
# https://github.com/material-components/material-components-web/pull/7158
dependency_overrides:
  sass: 1.32.10