name: samples_index
description: A visual index of Flutter samples
homepage: https://github.com/flutter/samples/tree/main/web/samples_index
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  json_annotation: ^4.7.0
  path: ^1.8.0
  yaml: ^3.1.0
  mdc_web: ^0.6.0
  # ^2.1.5 is no longer compatible with our overridden sass version
  # https://github.com/flutter/samples/issues/1472
  sass_builder: 2.1.4
  checked_yaml: ^2.0.1
  webdriver: ^3.0.0
  html: ^0.15.0

dev_dependencies:
  grinder: ^0.9.0
  flutter_lints: ^2.0.1
  test: ^1.12.0
  json_serializable: ^6.5.0
  build: ^2.3.0
  build_runner: ^2.3.0
  build_web_compilers: ^3.2.0
  image: ">=3.2.0 <5.0.0"

# waiting for the next material-components-web release.
# Once released, it will need to be rolled into package:mdc_web.
#
# https://github.com/material-components/material-components-web/pull/7158
# https://github.com/flutter/samples/issues/1472
dependency_overrides:
  sass: 1.32.10