name: federated_plugin_platform_interface
description: A platform interface for federated_plugin.
version: 0.0.1
homepage:

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  analysis_defaults:
    path: ../../../analysis_defaults
  flutter_test:
    sdk: flutter
