name: multiple_flutters_module
description: A module that is embedded in the multiple_flutters_ios and multiple_flutters_android sample code.

version: 1.0.0+1

environment:
  sdk: ^3.4.0-0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.6

  cupertino_icons: ^1.0.0

dev_dependencies:
  analysis_defaults:
    path: ../../../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.multiple_flutters_module
    iosBundleIdentifier: com.example.multipleFluttersModule
