name: flutter_module
description: An example Flutter module.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2

dev_dependencies:
  analysis_defaults:
    path: ../../../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  espresso: ">=0.2.0 <0.4.0"

flutter:
  uses-material-design: true

  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: dev.flutter.example.flutter_module
    iosBundleIdentifier: dev.flutter.example.flutterModule
