name: shared
description: Common data models required by our client and server
version: 1.0.0

environment:
  sdk: ^3.4.0-0

dependencies:
  freezed_annotation: ^2.1.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.1
  freezed: ^2.1.1
  json_serializable: ^6.4.0
  lints: ">=2.0.0 <6.0.0"
  test: ^1.16.0
