name: varfont_shader_puzzle
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^2.19.0-0
  flutter: ^3.7.0-0
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  shaders:
    - shaders/wavy.frag
    - shaders/wavy2.frag
    - shaders/wavy_circ.frag
    - shaders/color_split.frag
    - shaders/bw_split.frag
    - shaders/row_offset.frag
    - shaders/nothing.frag

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
    - family: Amstelvar
      fonts:
        - asset: assets/fonts/Amstelvar-Roman[GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,wdth,wght,opsz].ttf
