name: next_gen_ui_demo
description: Building a Next Generation UI in Flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  cupertino_icons: ^1.0.5
  extra_alignments: ^1.0.0+1
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  focusable_control_builder: ^1.0.1+1
  gap: ^3.0.0
  particle_field: ^1.0.0
  provider: ^6.0.5
  rnd: ^0.2.0
  vector_math: ^2.1.4
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo-Bold.ttf
        - asset: assets/fonts/Exo-Medium.ttf
  assets:
    - assets/images/
    - assets/fonts/
  shaders:
    - assets/shaders/orb_shader.frag
    - assets/shaders/ui_glitch.frag
