name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shared:
    path: ../shared

dev_dependencies:
  http: ^1.0.0
  lints: ^2.0.0
  test: ^1.15.0
