name: federated_plugin
description: A new flutter plugin project to demonstrate how to implement federated plugin.
version: 0.0.1

publish_to: "none"

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  federated_plugin_platform_interface:
    path: ../federated_plugin_platform_interface
  federated_plugin_web:
    path: ../federated_plugin_web
  federated_plugin_windows:
    path: ../federated_plugin_windows
  federated_plugin_macos:
    path: ../federated_plugin_macos

dev_dependencies:
  analysis_defaults:
    path: ../../../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.federated_plugin
        pluginClass: FederatedPlugin
      ios:
        pluginClass: SwiftFederatedPlugin
      web:
        default_package: federated_plugin_web
      windows:
        default_package: federated_plugin_windows
      macos:
        default_package: federated_plugin_macos
