name: desktop_photo_search
description: Search for Photos, using the Unsplash API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  built_collection: ^5.1.1
  built_value: ^8.3.0
  cupertino_icons: ^1.0.2
  file_selector: ^0.9.1
  flutter:
    sdk: flutter
  flutter_simple_treeview: ^3.0.0-nullsafety.1
  http: ^1.0.0
  logging: ^1.0.2
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8
  provider: ^6.0.2
  transparent_image: ^2.0.0
  url_launcher: ^6.1.1
  uuid: ^3.0.5
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 6c66ad23ee79749f30a8eece542cf54eaf157ed8

dev_dependencies:
  analysis_defaults:
    path: ../../analysis_defaults
  async: ^2.8.2
  build: ^2.2.1
  build_runner: ^2.1.7
  built_value_generator: ^8.3.0
  flutter_test:
    sdk: flutter
  grinder: ^0.9.0
  msix: ^3.9.2

flutter:
  uses-material-design: true

msix_config:
  display_name: Flutter Desktop Photo Search
  publisher_display_name: flutter.dev
  store: false # Set to true to deploy to Microsoft Store
  publisher: CN=01A6D5C0-D51A-4EEE-8DD0-F134DDD378F7
  identity_name: 16354flutter.dev.FlutterDesktopPhotoSearch
  msix_version: 1.0.0.1
  icons_background_color: "#ffffff"
  architecture: x64
  # See https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
  capabilities: "internetClient"
