name: grayscale_transformer
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.4.2
  image: ^4.1.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
