name: provider_shopper
description: A shopping app sample that uses Provider for state management.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Import the provider package.
  provider: ^6.0.2

  # plugin is not yet part of the flutter framework
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
