name: crashy
description: A Flutter app that knows how to crash in various ways.

dependencies:
  sentry: 0.0.6
  flutter:
    sdk: flutter

dev_dependencies:
  test: 0.12.21

flutter:
  uses-material-design: true
