name: provider_counter
description: >
  The starter Flutter application, but using Provider to manage state.

version: 1.0.0

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^2.0.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.7.0


flutter:
  uses-material-design: true
