name: provider_counter
description: >
  The starter Flutter application, but using Provider to manage state.
publish_to: none
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  cupertino_icons: ^1.0.3
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
