name: example
description: Charts-Flutter Demo
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  meta: ^1.1.1
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - preview.png
