name: Beta Branch CI

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  # Test all samples on the beta channel. Since the beta channel will soon be
  # promoted to stable, this branch is only concerned with the beta.
  Beta-CI:
    name: Test flutter beta channel
    runs-on: ${{ matrix.os }}
    if: github.repository == 'flutter/samples'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          channel: beta
      - run: flutter pub get && dart tool/ci_script.dart
  
  # Verify the Android add-to-app samples build and pass tests with the beta
  # channel.
  android-build:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
        with:
          channel: beta
      - run: ./tool/android_ci_script.sh

  # Verify the iOS add-to-app samples build and pass tests with the beta
  # channel.
  # ios-build:
  #   runs-on: macos-latest
  #   if: github.repository == 'flutter/samples'
  #   steps:
  #     - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
  #     - uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165
  #       with:
  #         distribution: 'zulu'
  #         java-version: '17'
  #     - uses: subosito/flutter-action@e938fdf56512cc96ef2f93601a5a40bde3801046
  #       with:
  #         channel: beta
  #     - run: ./tool/ios_ci_script.sh
