name: Beta Branch CI

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [beta]
  pull_request:
    branches: [beta]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  # Run the stable test script on the beta channel. Since this branch will soon
  # be merged into main as our stable-targeting code, this is the key thing we
  # need to test.
  stable-tests-on-beta:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'flutter/samples'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: beta
      - run: ./tool/flutter_ci_script_stable.sh
  # Verify the Android add-to-app samples build and pass tests with the beta
  # channel.
  android-build:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: beta
      - run: ./tool/android_ci_script.sh
  # Verify the iOS add-to-app samples build and pass tests with the beta
  # channel.
  ios-build:
    runs-on: macos-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
      - uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: beta
      - run: ./tool/ios_ci_script.sh
