name: Master Branch CI

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

defaults:
  run:
    shell: bash

jobs:
  flutter-tests:
    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.repository == 'flutter/samples'
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [stable, beta]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          channel: ${{ matrix.flutter_version }}
      - run: ./tool/flutter_ci_script_${{ matrix.flutter_version }}.sh
  android-build:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          channel: stable
      - run: ./tool/android_ci_script.sh
  ios-build:
    runs-on: macos-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748
      - uses: actions/setup-java@860f60056505705214d223b91ed7a30f173f6142
        with:
          distribution: 'zulu'
          java-version: '12.x'
      - uses: subosito/flutter-action@d8687e6979e8ef66d2b2970e2c92c1d8e801d7bf
        with:
          channel: stable
      - run: ./tool/ios_ci_script.sh
