name: Main Branch CI

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

defaults:
  run:
    shell: bash

jobs:
  flutter-tests:
    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.repository == 'flutter/samples'
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [stable, beta, master]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: ${{ matrix.flutter_version }}
      - run: ./tool/flutter_ci_script_${{ matrix.flutter_version }}.sh
  web-samples-index:
    name: web/samples_index config check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
      - run: |
          dart pub get
          dart run grinder generate
        working-directory: web/samples_index
  android-build:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: stable
      - run: ./tool/android_ci_script.sh
  ios-build:
    runs-on: macos-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      - uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: stable
      - run: ./tool/ios_ci_script.sh
