name: Main Branch CI

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight

defaults:
  run:
    shell: bash

jobs:
  flutter-tests:
    name: Test Flutter ${{ matrix.flutter_version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.repository == 'flutter/samples'
    strategy:
      fail-fast: false
      matrix:
        flutter_version: [stable, beta, master]
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
        with:
          channel: ${{ matrix.flutter_version }}
      - run: ./tool/flutter_ci_script_${{ matrix.flutter_version }}.sh

  web-samples-index:
    name: web/samples_index config check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
      - run: |
          dart pub get
          dart run grinder generate
        working-directory: web/samples_index

  # android-build:
  #   runs-on: ubuntu-latest
  #   if: github.repository == 'flutter/samples'
  #   steps:
  #     - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
  #     - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
  #       with:
  #         distribution: 'zulu'
  #         java-version: '17'
  #     - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
  #       with:
  #         channel: stable
  #     - run: ./tool/android_ci_script.sh

  ios-build:
    runs-on: macos-latest
    if: github.repository == 'flutter/samples'
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1
        with:
          channel: stable
      - run: ./tool/ios_ci_script.sh
