name: Verify web demos

# Declare default permissions as read only.
permissions: read-all

on: [push, pull_request]
jobs:
  verify-web-demos:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    strategy:
      matrix:
        flutter_version:
          - stable
          - beta
    steps:
      - name: Checkout
        uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
        with:
          submodules: true
          fetch-depth: 0
      - uses: subosito/flutter-action@6c2e035f2692eeac890d854df95630c72673f130
        with:
          channel: ${{ matrix.flutter_version }}
      - name: Init scripts
        run: dart pub get
        working-directory: web/_tool
      - name: Verify packages
        run: dart _tool/verify_packages.dart
        working-directory: web
