name: Verify web demos

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-web-demos:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    strategy:
      matrix:
        flutter_version:
          - stable
          # TODO(johnpryan): https://github.com/flutter/samples/issues/1469
          # - beta
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          submodules: true
          fetch-depth: 0
      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d
        with:
          channel: ${{ matrix.flutter_version }}
      - name: Init scripts
        run: dart pub get
        working-directory: web/_tool
      - name: Verify packages
        run: dart run _tool/verify_packages.dart
        working-directory: web
