name: Verify web demos

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-web-demos:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    strategy:
      matrix:
        flutter_version:
          - stable
          - beta
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: true
          fetch-depth: 0
      - uses: subosito/flutter-action@de3cdb9a4b2f535dc0fa0da445a46b10b1bfefc7
        with:
          channel: ${{ matrix.flutter_version }}
      - name: Init scripts
        run: dart pub get
        working-directory: web/_tool
      - name: Verify packages
        run: dart _tool/verify_packages.dart
        working-directory: web
