name: Verify web demos

# Declare default permissions as read only.
permissions: read-all

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-web-demos:
    runs-on: ubuntu-latest
    if: github.repository == 'flutter/samples'
    strategy:
      matrix:
        flutter_version:
          - stable
          # TODO(johnpryan): https://github.com/flutter/samples/issues/1469
          # - beta
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          submodules: true
          fetch-depth: 0
      - uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff
        with:
          channel: ${{ matrix.flutter_version }}
      - name: Init scripts
        run: dart pub get
        working-directory: web/_tool
      - name: Verify packages
        run: dart run _tool/verify_packages.dart
        working-directory: web
